[http]
  [http.middlewares]
    [http.middlewares.http2https.redirectScheme]
      scheme = "https"
    [http.middlewares.sts.headers]
      forceSTSHeader = true
      stsSeconds = 31536000
    [http.middlewares.security.headers]
      frameDeny = true
      contentTypeNosniff = true
      browserXssFilter = true
